### ISSUE TITLE
What is the difficulty of translating cities into geographic coordinates?

### ISSUE THREAD

**Issue by DailinYee** [Ro0oot/spiritualist#4]

**Comment by Ro0oot** [comment]
The part of translating city into coordinates is fine. We just have some issue with the data type, the lons&lats should be float and is float on my end, but when Tian tried to read my file, the became string, weird.

**Comment by tianBreznik** [comment]
Root and I have resolved this. The dataframe now contains a longitude and latitude column, which are then concatenated into a Point() object when generating the .geojson file. I am now closing this issue,
